package com.kankangames.shadowofroles.game.models.roles.properties;

public enum RoleAttribute {
    ROLE_BLOCK_IMMUNE,
    CAN_ROLE_BLOCK,
    KNOWS_TEAM_MEMBERS,
    HAS_POST_DEATH_EFFECT,
    REVIVES_AFTER_DEATH,
    HAS_HEALING_ABILITY,
    HAS_ATTACK_ABILITY,
    CAN_KILL_1V1,
    HAS_BLIND_ABILITY,
    HAS_DISGUISE_ABILITY,
    HAS_IMMUNE_ABILITY,
    WINS_ALONE,
    MUST_BE_LAST_STANDING,
    CAN_WIN_WITH_ANY_TEAM,
    MUST_SURVIVE_UNTIL_END,
    MUST_DIE_TO_WIN,
    HAS_OTHER_WIN_CONDITION
}
